source 'http://chef.sjc1.sendgrid.net:26200'
source 'https://api.berkshelf.com'

cookbook 'ci_dependencies', path: 'cookbooks/ci_dependencies'
cookbook 'golang', git: 'https://github.com/NOX73/chef-golang.git'


