---
driver:
  name: vagrant
  customize:
    memory: 1024
    natdnshostresolver1: "off"
    natdnsproxy1: "off"

provisioner:
  name: chef_solo

platforms:
  - name: sendgrid_go_segment_chef-11.12.4.box
    driver:
      box: sendgrid_centos-6.5_chef-11.12.4.box
      box_url: 'http://repo.sjc1.sendgrid.net/images/vagrant/sendgrid_centos-6.5_chef-11.12.4.box'

suites:
  - name: default
    run_list:
      - recipe[go_segment_base_box::default]
    attributes:
      go_segment_base_box:
        virtualbox:
          guest_additions:
            # The VirtualBox additions are already deleted from the Opscode
            # base boxes, and .vbox_version is in a different place than ours.
            download: true
            version_file: /home/vagrant/.vbox_version
